service: serverless-express-sample

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1

functions:
  app:
    handler: dist/handler.main
    events:
      - http:
          method: ANY
          path: "/"
      - http:
          method: ANY
          path: "{proxy+}"
