service: serverless-express-sample

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1

functions:
  app:
    # sls deploy でデプロイ後、Lambdaのhandler設定が「main.myhandler」になっていなかったら直す
    handler: src/handler.myhandler
    events:
      - http:
          method: ANY
          path: "/"
      - http:
          method: ANY
          path: "{proxy+}"

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true # enable auto-packing of external modules
